// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PP.EF;

#nullable disable

namespace PP.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    [Migration("20220607114236_AddOrderTables")]
    partial class AddOrderTables
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("PP.EF.models.Customers", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"), 1L, 1);

                    b.Property<string>("email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("id");

                    b.HasIndex("email")
                        .IsUnique();

                    b.ToTable("customers", (string)null);
                });

            modelBuilder.Entity("PP.EF.models.Goods", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"), 1L, 1);

                    b.Property<string>("name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("price")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("money")
                        .HasDefaultValue(0m);

                    b.Property<float>("rest")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("real")
                        .HasDefaultValue(0f);

                    b.HasKey("id");

                    b.ToTable("goods", (string)null);
                });

            modelBuilder.Entity("PP.EF.models.OrderRows", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"), 1L, 1);

                    b.Property<int>("goodid")
                        .HasColumnType("int");

                    b.Property<int>("orderid")
                        .HasColumnType("int");

                    b.Property<decimal>("price")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(15,4)")
                        .HasDefaultValue(0m);

                    b.Property<decimal>("quantity")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(15,4)")
                        .HasDefaultValue(0m);

                    b.Property<decimal>("summ")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("decimal(15,4)")
                        .HasComputedColumnSql("[quantity]*[price]");

                    b.HasKey("id");

                    b.HasIndex("goodid");

                    b.HasIndex("orderid");

                    b.ToTable("o_rows", (string)null);
                });

            modelBuilder.Entity("PP.EF.models.Orders", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"), 1L, 1);

                    b.Property<string>("comment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("customerid")
                        .HasColumnType("int");

                    b.Property<decimal>("summ")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(15,4)")
                        .HasDefaultValue(0m);

                    b.HasKey("id");

                    SqlServerKeyBuilderExtensions.IsClustered(b.HasKey("id"));

                    b.HasIndex("customerid");

                    SqlServerIndexBuilderExtensions.IncludeProperties(b.HasIndex("customerid"), new[] { "id", "summ" });

                    b.ToTable("orders", (string)null);
                });

            modelBuilder.Entity("PP.EF.models.OrderRows", b =>
                {
                    b.HasOne("PP.EF.models.Goods", "good")
                        .WithMany()
                        .HasForeignKey("goodid")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PP.EF.models.Orders", "order")
                        .WithMany("rows")
                        .HasForeignKey("orderid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("good");

                    b.Navigation("order");
                });

            modelBuilder.Entity("PP.EF.models.Orders", b =>
                {
                    b.HasOne("PP.EF.models.Customers", "customer")
                        .WithMany()
                        .HasForeignKey("customerid")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("customer");
                });

            modelBuilder.Entity("PP.EF.models.Orders", b =>
                {
                    b.Navigation("rows");
                });
#pragma warning restore 612, 618
        }
    }
}
